// <auto-generated />
using System;
using BudgetMe.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetMe.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417114400_ReferenceNumber")]
    partial class ReferenceNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankTransactionCategory", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "TransactionsId");

                    b.HasIndex("TransactionsId");

                    b.ToTable("BankTransactionCategory");
                });

            modelBuilder.Entity("BudgetMe.API.Features.Bindings.Models.Binding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Binding");
                });

            modelBuilder.Entity("BudgetMe.API.Features.Categories.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("Name", "TransactionTypeId")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32b90ecf-51e6-48a8-a9db-cf8ca9a79ab5"),
                            IsSystem = true,
                            Name = "Household",
                            TransactionTypeId = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db")
                        },
                        new
                        {
                            Id = new Guid("8e9f5d5d-fbed-4748-8d5c-53b1d4abb84f"),
                            IsSystem = true,
                            Name = "Food",
                            TransactionTypeId = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db")
                        },
                        new
                        {
                            Id = new Guid("e7b9dd86-7c8e-48f1-acd6-ace5e8909c23"),
                            IsSystem = true,
                            Name = "Entertainment",
                            TransactionTypeId = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db")
                        },
                        new
                        {
                            Id = new Guid("1d65afc4-0edf-464e-8cab-24f7a175f043"),
                            IsSystem = true,
                            Name = "Transportation",
                            TransactionTypeId = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db")
                        },
                        new
                        {
                            Id = new Guid("3a75b398-be8f-410c-a3d0-3f9ca395ef98"),
                            IsSystem = true,
                            Name = "Gift",
                            TransactionTypeId = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db")
                        },
                        new
                        {
                            Id = new Guid("0ecb7853-21b1-4e54-9bc2-8e2099e0f2f9"),
                            IsSystem = true,
                            Name = "Other",
                            TransactionTypeId = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db")
                        },
                        new
                        {
                            Id = new Guid("8e19c4f0-6051-4ec3-b306-b43616379436"),
                            IsSystem = true,
                            Name = "Earnings",
                            TransactionTypeId = new Guid("520a21ea-e710-4eb6-abef-5c4a93d55720")
                        },
                        new
                        {
                            Id = new Guid("13237788-358d-48ae-a686-7100aa4e1333"),
                            IsSystem = true,
                            Name = "Gift",
                            TransactionTypeId = new Guid("520a21ea-e710-4eb6-abef-5c4a93d55720")
                        },
                        new
                        {
                            Id = new Guid("13921db7-47f2-4e1a-b87e-c75530164533"),
                            IsSystem = true,
                            Name = "Other",
                            TransactionTypeId = new Guid("520a21ea-e710-4eb6-abef-5c4a93d55720")
                        });
                });

            modelBuilder.Entity("BudgetMe.API.Features.Transactions.Models.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("BankTransaction");
                });

            modelBuilder.Entity("BudgetMe.API.Features.Transactions.Models.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("520a21ea-e710-4eb6-abef-5c4a93d55720"),
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("a96bcd4c-c469-430f-951e-e3492f1de2db"),
                            Name = "Expense"
                        });
                });

            modelBuilder.Entity("BankTransactionCategory", b =>
                {
                    b.HasOne("BudgetMe.API.Features.Categories.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetMe.API.Features.Transactions.Models.BankTransaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetMe.API.Features.Bindings.Models.Binding", b =>
                {
                    b.HasOne("BudgetMe.API.Features.Categories.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetMe.API.Features.Categories.Models.Category", b =>
                {
                    b.HasOne("BudgetMe.API.Features.Transactions.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("BudgetMe.API.Features.Transactions.Models.BankTransaction", b =>
                {
                    b.HasOne("BudgetMe.API.Features.Transactions.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionType");
                });
#pragma warning restore 612, 618
        }
    }
}
